#! /bin/sh
# **************************************************************************
# Regenerate all files which are constructed by the autoconf, automake
# and libtool tool-chain. Note: only developers should need to use this
# script.
#
# Authors:
#   Morten Eriksen <mortene@sim.no>
#   Lars J. Aas <larsa@sim.no>

wd=`echo $0 | sed 's,[^\\/]*$,,g'`
me=`echo $0 | sed 's,.*/,,g'`

cd $wd
if test ! -f ./$me; then
  echo >&2 "$me: error: unexpected problem with your shell - bailing out"
  exit 1
fi

verbose=false # | verbose=true

for arg in $@; do
  case "$arg" in
  -v | --verbose)
    verbose=true
    ;;
  --clean)
    ( $verbose && set -x;
      rm -f aclocal.m4 config.h.in configure stamp-h*
      rm -f cfg/{config.guess,config.sub,depcomp,install-sh,ltconfig,ltmain.sh,missing,mkinstalldirs}
      find . -name Makefile.in -print | xargs rm -f
    )
    exit 0
    ;;
  --add)
    AUTOMAKE_ADD="--copy --add-missing"
    ;;
  *)
    echo >&2 "$me: error: don't understand argument \"$arg\""
    DIE=true
    ;;
  esac
done

AUTOCONF_VER=2.5[02]
AUTOMAKE_VER=1.5
LIBTOOL_VER=1.3.5

PROJECT=SoXt
GUI=Xt
MACRODIR=cfg/m4

SUBPROJECTS="$MACRODIR data"
SUBPROJECTNAMES="SoXtMacros SoXtData"
: ${AUTOMAKE_ADD=}

echo "Checking the installed configuration tools..."

if test -z "`autoconf --version | grep \" $AUTOCONF_VER\" 2> /dev/null`"; then
  cat <<EOF

  Invalid Version of Autoconf
  ---------------------------
  You must use the CVS development version of autoconf ($AUTOCONF_VER)
  to generate configure information and Makefiles for $PROJECT.
EOF
  DIE=true
fi

if test -z "`automake --version | grep \" $AUTOMAKE_VER\" 2> /dev/null`"; then
  cat <<EOF

  Invalid Version of Automake
  ---------------------------
  You must use the CVS development version of automake to ($AUTOMAKE_VER)
  to generate configure information and Makefiles for $PROJECT.

  The CVS automake repository can be fetched by running the following
  set of commands:

  $ cvs -d :pserver:anoncvs@anoncvs.cygnus.com:/cvs/automake login
  $ cvs -d :pserver:anoncvs@anoncvs.cygnus.com:/cvs/automake co automake
EOF
  DIE=true
fi

if test -z "`libtool --version | grep \" $LIBTOOL_VER \" 2> /dev/null`"; then
  cat <<EOF

  Invalid Version of Libtool
  --------------------------
  You must have libtool version $LIBTOOL_VER installed to generate
  configure information and Makefiles for $PROJECT.

  Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-1.3.5.tar.gz
EOF
  DIE=true
fi

set $SUBPROJECTNAMES
num=1
for project in $SUBPROJECTS; do
  test -d $project || {
    echo ""
    echo "Could not find subdirectory '$project'."
    echo "It was probably added after you initially fetched $PROJECT."
    echo "To add the missing module, run 'cvs co $1' from the $PROJECT"
    echo "base directory."
    echo ""
    echo "To do a completely fresh cvs checkout of the whole $PROJECT module,"
    echo "(if all else fails), remove $PROJECT and run:"
    echo ""
    echo "  cvs -z3 -d :pserver:cvs@cvs.sim.no:/export/cvsroot co -P $PROJECT"
    DIE=true
  }
  num=`expr $num + 1`
  shift
done

# abnormal exit?
${DIE=false} && echo "" && echo >&2 "$me: error: aborting because of errors..." && exit 1

# **************************************************************************
# grepping stderr makes the commands weird

# generate aux/aclocal.m4
echo "Running aclocal..."
( $verbose && set -x;
  aclocal -I $MACRODIR
)

# generate configure
echo "Running autoconf..."
( ( $verbose && set -x;
  autoconf
) 3>&1 1>&2 2>&3 | grep -v 'AR_FLAGS$' ) 3>&1 1>&2 2>&3

# generate config.h.in
echo "Running autoheader..."
( ( $verbose && set -x;
  autoheader
) 3>&1 1>&2 2>&3 | grep -v 'is unchanged$' ) 3>&1 1>&2 2>&3

# generate Makefile.in templates
echo "Running automake..."
( ( $verbose && set -x;
  automake $AUTOMAKE_ADD
) 3>&1 1>&2 2>&3 | egrep -v 'directory should not| installing ' ) 3>&1 1>&2 2>&3

